export const IMAGE_TYPES = {
    PRODUCT_1:require("../assetes/image/Bacon.webp"),
    PRODUCT_2:require("../assetes/image/Chicken Boneless.webp"),
    PRODUCT_3:require("../assetes/image/Chicken Seekh Kebab.webp"),
    PRODUCT_4:require("../assetes/image/Chicken Steak.webp"),
    PRODUCT_5:require("../assetes/image/chps.webp"),
    PRODUCT_6:require("../assetes/image/Cubes.webp"),
    PRODUCT_7:require("../assetes/image/dian Basa Fillet.webp"),
    PRODUCT_8:require("../assetes/image/eggs.webp"),
    PRODUCT_9:require("../assetes/image/Fillet.webp"),
    PRODUCT_10:require("../assetes/image/mutton bonless.webp"),
    PRODUCT_11:require("../assetes/image/Mutton.webp"),
    PRODUCT_12:require("../assetes/image/Pork Mince.webp"),
    PRODUCT_13:require("../assetes/image/Pork_Belly_Cubes.webp"),
    PRODUCT_14:require("../assetes/image/sole.webp"),
    PRODUCT_15:require("../assetes/image/Tuna.webp"),
    PRODUCT_16:require("../assetes/image/bone.webp"),
    PRODUCT_17:require("../assetes/image/roll.webp"),
    }